# Generated by Django 3.2.13 on 2022-05-27 07:12

from django.db import migrations, models
import usersite.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralDayDescriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('day_title', models.CharField(max_length=200)),
                ('daily_image', models.ImageField(upload_to=usersite.models.daily_image_way)),
            ],
            options={
                'verbose_name': 'day',
                'verbose_name_plural': 'Days',
            },
        ),
    ]
