# Generated by Django 3.2.13 on 2022-05-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0003_alter_generaldaydescriptionmodel_day_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaldaydescriptionmodel',
            name='daily_image',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
