# Generated by Django 3.2.13 on 2022-05-27 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0005_dayarticlemodel_dayaudiomodel_dayphotomodel_dayvideomodel_itemcategorymodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayarticlemodel',
            options={'verbose_name': 'article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.CreateModel(
            name='DayEventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='empty title')),
                ('description', models.TextField()),
                ('event_time', models.TimeField()),
                ('url', models.CharField(blank=True, max_length=100)),
                ('date', models.DateTimeField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usersite.generaldaydescriptionmodel')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.AddField(
            model_name='dayarticlemodel',
            name='parent_event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='usersite.dayeventmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dayaudiomodel',
            name='parent_event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='usersite.dayeventmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dayphotomodel',
            name='parent_event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='usersite.dayeventmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dayvideomodel',
            name='parent_event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='usersite.dayeventmodel'),
            preserve_default=False,
        ),
    ]
