# Generated by Django 3.2.13 on 2022-05-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0006_auto_20220527_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostItemsListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.IntegerField()),
                ('tanks', models.IntegerField()),
                ('battle_armored_vehicle', models.IntegerField()),
                ('artilery_system', models.IntegerField()),
                ('rszo', models.IntegerField()),
                ('antyair_missle', models.IntegerField()),
                ('airplanes', models.IntegerField()),
                ('helicopters', models.IntegerField()),
                ('vehicle', models.IntegerField()),
                ('ships_and_boats', models.IntegerField()),
                ('bpla', models.IntegerField()),
                ('special_vehicle', models.IntegerField()),
                ('rockets', models.IntegerField()),
            ],
            options={
                'verbose_name': 'or change items info',
                'verbose_name_plural': 'Lost items list',
            },
        ),
    ]
