# Generated by Django 3.2.13 on 2022-05-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0007_lostitemslistmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitemslistmodel',
            name='airplanes',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='lostitemslistmodel',
            name='antyair_missle',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='lostitemslistmodel',
            name='artilery_system',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='lostitemslistmodel',
            name='battle_armored_vehicle',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='lostitemslistmodel',
            name='bpla',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='lostitemslistmodel',
            name='helicopters',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='lostitemslistmodel',
            name='rockets',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='lostitemslistmodel',
            name='rszo',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='lostitemslistmodel',
            name='ships_and_boats',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='lostitemslistmodel',
            name='special_vehicle',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='lostitemslistmodel',
            name='tanks',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='lostitemslistmodel',
            name='team',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='lostitemslistmodel',
            name='vehicle',
            field=models.CharField(max_length=11),
        ),
    ]
