# Generated by Django 3.2.13 on 2022-05-28 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0010_auto_20220527_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lostitemslistmodel',
            old_name='vehicle',
            new_name='vehicles',
        ),
    ]
