# Generated by Django 3.2.13 on 2022-05-28 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0012_remove_dayeventmodel_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayeventmodel',
            name='date',
        ),
    ]
