# Generated by Django 3.2.13 on 2022-05-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0014_auto_20220528_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayeventmodel',
            name='event_preview',
            field=models.ImageField(blank=True, upload_to='media/images/event_preview/'),
        ),
    ]
