# Generated by Django 3.2.13 on 2022-05-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0015_dayeventmodel_event_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayeventmodel',
            name='event_preview',
            field=models.ImageField(blank=True, default='https://icon-library.com/images/img-icon/img-icon-11.jpg', upload_to='media/images/event_preview/'),
        ),
    ]
