# Generated by Django 3.2.13 on 2022-05-28 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0017_auto_20220528_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayaudiomodel',
            old_name='video',
            new_name='media',
        ),
        migrations.RenameField(
            model_name='dayphotomodel',
            old_name='image',
            new_name='media',
        ),
        migrations.RenameField(
            model_name='dayvideomodel',
            old_name='video',
            new_name='media',
        ),
    ]
