# Generated by Django 3.2.13 on 2022-05-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0018_auto_20220528_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayeventmodel',
            name='quote',
            field=models.TextField(blank=True),
        ),
    ]
