# Generated by Django 3.2.13 on 2022-05-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0019_dayeventmodel_quote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayeventmodel',
            old_name='quote',
            new_name='quote1',
        ),
        migrations.AddField(
            model_name='dayeventmodel',
            name='quote2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dayeventmodel',
            name='quote3',
            field=models.TextField(blank=True),
        ),
    ]
