# Generated by Django 3.2.13 on 2022-05-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0020_auto_20220529_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayaudiomodel',
            name='media',
            field=models.FileField(upload_to='media/audio/%Y/%m/%d'),
        ),
    ]
